### ISSUE TITLE
login/logout broken

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#119]
It's not possible to log out if logged in on staging -> logout link yields a hidden 404,
https://imi-map-staging.f4.htw-berlin.de/

and it seems as if it is not necessary to log in at all? If I delete cookies, I'm still logged in.

**Comment by ViviZa** [comment]
When I try to sign up, I get an empty page ...
Login also directs me to an empty page, I am not sure if I am signed up now or not. Something is not working properly.
![signup](https://user-images.githubusercontent.com/13219760/28512889-1184d564-7054-11e7-8091-4a0a8796b625.png)

**Comment by danistep** [comment]
okay Vivi's problem should be fixed as soon as we merge maps branch - not all the routes were probably set up, because we needed to merge them first

**Comment by danistep** [comment]
login/logout link should be fixed in the same commit, because our original login form was using post to the same sessions controller that we got rid of.

**Comment by danistep** [comment]
There is one other issue, fix for which I'll push after i leave my corporate network that leads to 500, Connection errors/exceptions. Is our staging server inside domain that we are trying to access?
