### ISSUE TITLE
Fix gmaps4rails integration

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#37]
The views call a method "gmaps" which was not available after the updates, as a shortcut I just replaced it with a dummy in application_helper.rb:
  ```# TBD Update gmaps4rails: this should return appropriate
  # javascript to include the map.
  def gmaps(hash={})
    "MAP WAS HERE"
  end
```

It is called from 4 locations - search for "gmaps(" - these are all broken now as they call above dummy.

I've created a branch with the (mostly - one of the maps doesn't show there, either - ) working version before the updates:

https://github.com/imimaps/imimaps/tree/before-update-gmaps-working

(which module defined the above gmaps() method and where?? was it an old version of the gem?)

Steps
- update gem to the newest version. 
- read documentation
- set up an example in a new app, to understand how it works
- fix integration in IMI-Maps.

**Comment by danistep** [comment]
Replaced with leaflet maps
