### ISSUE TITLE
broken logo on 500 page

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#46]
500 page has broken logo link, logo should be smaller

development shows debugging info  instead of  500 page, thus a bit tricky to test - switch to production environment to see it.

**Comment by ThomasSweet** [comment]
haven't been able to figure out how to add a home button in html because i dont know what file to link to. i guess i will have to go back to the rails tutorial.

**Comment by danistep** [comment]
Fixed and merged https://github.com/imimaps/imimaps/pull/81
