### ISSUE TITLE
Remove Guide / Static Pages

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#56]
http://localhost:3000/de/overview
- everything under "Guide" can be removed.

**Comment by sperezalonso** [comment]
Should I delete only the pop-up menu or the whole Guide button?

**Comment by bkleinen** [comment]
All pages related to the guide.

**Comment by danistep** [comment]
Done in branch https://github.com/imimaps/imimaps/tree/removeGuide but not merged
