### ISSUE TITLE
Create Better Example Data for Development

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#60]
... with factory Girl.
or maybe not with factory girl, see https://robots.thoughtbot.com/factory_girl-for-seed-data, rather
organise existing seeds better:
- create a rake tasks that includes all files in db/seeds/ and split up the huge file into chunks
- use faker gem to generate better test data : https://github.com/stympy/faker
- raise an exception when run in production environment, see for example 
https://gist.github.com/ChuckJHardy/997746

**Comment by ViviZa** [comment]
Bearbeitungsstand Showtime:
seed.rb liest nun aus dem Ordner seed jede Datei aus - in diesem Ordner liegt die ehemalige seed.rb aufgeteilt in mehreren Dateien, hat leider nur teilweise funktioniert
