### ISSUE TITLE
Check if Bootstrap can be updated

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#65]
in fact, for rails 5 it will have to be updated: 

gem 'bootstrap-sass', '2.1' # not compatible with sass-rails 5, rails 5 needs sass-rails 5.0.6

# letzte kombi für bootstrap 2:
#gem 'sass-rails', '=> 3.2'
#gem 'bootstrap-sass', '~> 2.3.2.2'

there's an upgrade guide: https://www.bootply.com/bootstrap-3-migration-guide

how to upgrade a rails app:
http://www.outofscope.com/upgrading-bootstrap-from-2-to-3-or-between-any-major-versions/

**Comment by ViviZa** [comment]
https://github.com/imimaps/imimaps/pull/99
