### ISSUE TITLE
S008: Show and Validate Internship Duration automatically

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#91]
such that the Admin doesn't have to calculate it manually any more.

Given that the internship information is already there (which it is) - this is the URMETER with 2 Points.

**Comment by ViviZa** [comment]
-saving possible: 
without dates
<19 weeks

**Comment by danistep** [comment]
Fixed here
https://github.com/imimaps/imimaps/pull/94

**Comment by ViviZa** [comment]
Bearbeitungsstand der Showtime:
eingebaut in der Admin und in der User-View von Internships, funktioniert lokal, View-Test, Model-Test
