### ISSUE TITLE
Create a Statistic: Which Countries were visited in the last semester

### ISSUE THREAD

**Issue by bkleinen** [imimaps/imimaps#93]
create list with how many students were in wich country per semester.
Details will be added.

**Comment by ViviZa** [comment]
it was done with https://github.com/imimaps/imimaps/pull/100

**Comment by ViviZa** [comment]
Bearbeitungsstand der Showtime: 
lokal funktioniert es, Statistiken sind für alle Semester durch ein Dropdown einzusehen, Tests wurden nicht geschrieben
